// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanhR8uxGQKwSlbZinflb2PJ8EKMlEZmA',
    appId: '1:753363370423:web:4e52d899d6e33140162832',
    messagingSenderId: '753363370423',
    projectId: 'lineup-hockey-app',
    authDomain: 'lineup-hockey-app.firebaseapp.com',
    storageBucket: 'lineup-hockey-app.firebasestorage.app',
    measurementId: 'G-YT2S9BSLXW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV5Pz6JX9XcVArnmMZSDKWbEdzmJO9-s0',
    appId: '1:753363370423:android:9eb6c50babdbdcdb162832',
    messagingSenderId: '753363370423',
    projectId: 'lineup-hockey-app',
    storageBucket: 'lineup-hockey-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOobw8cQnxskZKII6uPYCcL_7OE8L7pkY',
    appId: '1:753363370423:ios:e2faf2ad03fc0cf1162832',
    messagingSenderId: '753363370423',
    projectId: 'lineup-hockey-app',
    storageBucket: 'lineup-hockey-app.firebasestorage.app',
    iosBundleId: 'com.example.lineup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOobw8cQnxskZKII6uPYCcL_7OE8L7pkY',
    appId: '1:753363370423:ios:e2faf2ad03fc0cf1162832',
    messagingSenderId: '753363370423',
    projectId: 'lineup-hockey-app',
    storageBucket: 'lineup-hockey-app.firebasestorage.app',
    iosBundleId: 'com.example.lineup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanhR8uxGQKwSlbZinflb2PJ8EKMlEZmA',
    appId: '1:753363370423:web:cb682e780c493c57162832',
    messagingSenderId: '753363370423',
    projectId: 'lineup-hockey-app',
    authDomain: 'lineup-hockey-app.firebaseapp.com',
    storageBucket: 'lineup-hockey-app.firebasestorage.app',
    measurementId: 'G-J0G50H6JL1',
  );
}
